### ISSUE TITLE
400 No required SSL certificate was sent

### ISSUE THREAD

**Issue by Harrrrry** [Mastercard/oauth1-signer-nodejs#17]
Hello,

I am getting the 400 No required SSL certificate was sent error in body while calling the MEA wallet api.
Can any one help me to solve this issue.

**Generating the key**
genrateKey: (req, res) => {
    console.log("I am in generateKey api");
    const p12Content = fs.readFileSync(
      path.resolve(__dirname, "../public/images/cert.P12"),
      "binary"
    );
    const p12Asn1 = forge.asn1.fromDer(p12Content, false);

    const p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, "paswword");
    const keyBags = p12.getBags({
      bagType: forge.pki.oids.pkcs8ShroudedKeyBag,
    });
    var bag = keyBags[forge.pki.oids.pkcs8ShroudedKeyBag][0];
    var privateKey = bag.key;
    const signingKey = forge.pki.privateKeyToPem(privateKey);
    console.log("generateKey is working fine");
    return signingKey;
 },
  
**Generating the token**
 genrateToken: async (req, res) => {
    console.log("I am in generateToken api");
    const signingKey = await CommonController.genrateKey();

    const consumerKey = "11";
    const uri = "https://sandbox.api.mastercard.com/service";
    const method = "POST";
    const payload = "Hello world!";

    const oauth = require("mastercard-oauth1-signer");
    const authHeader = oauth.getAuthorizationHeader(
      uri,
      method,
      payload,
      consumerKey,
      signingKey
    );
    //console.log(authHeader);
    // res.send(authHeader);
    return authHeader;
  },
**Calling the MEA apis**
 getUserList: async (req, res) => {
    console.log("I am in userlist api");
    var request = require("request");
    var token = await CommonController.genrateToken(); // generating successfully
    request(
      {
        method: "GET",
        url:
          "https://mmtb2b.test.meawallet.com/mmt/tokenization/v1/user?page=&size=&status=&from=",
        headers: {
          "Content-Type": "application/json",
          "Mea-Trace-Id": "sad23423-234d-asdas-123123-se234234",
          Authorization: token,
        },
      },
      function (error, response, body) {
        console.log("Error:", error);
        console.log("Status:", response.statusCode);
        console.log("Headers:", JSON.stringify(response.headers));
        console.log("Response:", body);
      }
    );
  },

**Comment by jaaufauvre** [comment]
Hi @Harrrrry 

Thanks for having opened this issue, but it doesn't seem to be relevant to this project: I can reproduce the "_No required SSL certificate was sent_" error by simply pasting the URL in my web browser. 

This GitHub project is for generating a Mastercard API compliant OAuth signature. See also: https://mstr.cd/30cHTMQ. Please check the "MEA wallet" API actually expects a OAuth 1.0a signature (it looks like Mutual TLS to me).

Also, if it can help here is a page you can use to get support when integrating with a Mastercard API: https://developer.mastercard.com/support/

Thanks!

**Comment by Harrrrry** [comment]
@jaaufauvre Hello,

I am stuck.
I am using your code and able to generate the signing key and then token for authorization but when I use the generated token in MEA API then in response, showing me the below error.

`Error: Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Object.createSecureContext (_tls_common.js:149:17)
    at Object.connect (_tls_wrap.js:1585:48)
    at Agent.createConnection (https.js:132:22)
    at Agent.createSocket (_http_agent.js:321:26)
    at Agent.addRequest (_http_agent.js:275:10)
    at new ClientRequest (_http_client.js:297:16)
    at Object.request (https.js:316:10)
    at Request.start (/home/ubuntu/MEA/node_modules/request/request.js:751:32)
    at Request.end (/home/ubuntu/MEA/node_modules/request/request.js:1505:10)
    at end (/home/ubuntu/MEA/node_modules/request/request.js:564:14) {
  opensslErrorStack: [ 'error:0906A065:PEM routines:PEM_do_header:bad decrypt' ],
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}
`

Not understand what is the problem.
Is problem related to signing key process, authorization process or MEA API
Can you check my code, am I doing the right way?

**Comment by TutteRamson** [comment]
This signer library is meant for making calls to the services hosted on [Mastercard Developers](https://developer.mastercard.com/). The tokenization API you are trying to call is from [MEAWallet.com](https://meawallet.com/) and that is not hosted on Mastercard Developers.

You are free to extend it and make it work with other service providers. However, Mastercard's support is limited to cases where a Mastercard API that is hosted on Mastercard Developers is involved.

**Comment by Harrrrry** [comment]
@TutteRamson thanks,
const payload = "Hello world!";
const oauth = require('mastercard-oauth1-signer');
const authHeader = oauth.getAuthorizationHeader(uri, method, payload, consumerKey, signingKey);

I am confuse about the payload when i call the POST api.
Should i need to encode or anything to make it work.

I am sending the string which is converted by JSON and then auth token is created but when i use that token in MEA api then it give me the 401 status code.
UNAUTHORIZED | 401 | Authentication is expired or unauthorized request

Its look like the auth token is not generated perfectly?

Any help on this?
Thanks

**Comment by TutteRamson** [comment]
We suggest checking with the developer support team of MEAWallet.com. They may be able to point out the reason for not accepting the signature or provide you with their version of the library or SDK.

**Comment by Harrrrry** [comment]
ok
